
package ar.edu.ubp.das.restaurante2.services.jaxws;

import com.fasterxml.jackson.core.JsonLocation;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.1
 * Generated source version: 3.0.1
 * 
 */
@XmlRootElement(name = "JsonProcessingException", namespace = "http://services.restaurante2.das.ubp.edu.ar/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "JsonProcessingException", namespace = "http://services.restaurante2.das.ubp.edu.ar/", propOrder = {
    "location",
    "message",
    "originalMessage",
    "processor"
})
public class JsonProcessingExceptionBean {

    private JsonLocation location;
    private String message;
    private String originalMessage;
    private Object processor;

    /**
     * 
     * @return
     *     returns JsonLocation
     */
    public JsonLocation getLocation() {
        return this.location;
    }

    /**
     * 
     * @param location
     *     the value for the location property
     */
    public void setLocation(JsonLocation location) {
        this.location = location;
    }

    /**
     * 
     * @return
     *     returns String
     */
    public String getMessage() {
        return this.message;
    }

    /**
     * 
     * @param message
     *     the value for the message property
     */
    public void setMessage(String message) {
        this.message = message;
    }

    /**
     * 
     * @return
     *     returns String
     */
    public String getOriginalMessage() {
        return this.originalMessage;
    }

    /**
     * 
     * @param originalMessage
     *     the value for the originalMessage property
     */
    public void setOriginalMessage(String originalMessage) {
        this.originalMessage = originalMessage;
    }

    /**
     * 
     * @return
     *     returns Object
     */
    public Object getProcessor() {
        return this.processor;
    }

    /**
     * 
     * @param processor
     *     the value for the processor property
     */
    public void setProcessor(Object processor) {
        this.processor = processor;
    }

}
